### ISSUE TITLE
EConflict on npm install

### ISSUE THREAD

**Issue by Mathemagiks** [leonardreidy/ngbootui#17]
npm install raises an EConflict error:

`ECONFLICT Unable to find suitable version for angular`

Add resolutions to bower.json to resolve: 

`  "resolutions": {
  "angular": "~1.5.0"
  }`

**Comment by leonardreidy** [comment]
Thank you Sharon! I will implement the fix right away.

**Comment by leonardreidy** [comment]
I experimented with your fix and it turns out that the following resolution works best: 

`"resolutions": {
    "angular": ">=1.4.0"
  }`

The more specific resolution raises some other issues with Angular Bootstrap and other dependencies. I will close the issue shortly! Thanks again for your help.

**Comment by leonardreidy** [comment]
More extensive tests indicate that the given resolutions key/value pair was inadequate. Instead, I've decided to upgrade all angular specific dependencies except angular-bootstrap to v.1.6.2, and angular-bootstrap to 2.5.0. 

The new resolutions object: 

`"resolutions": {
     "angular": ">=1.6.2"
}`
